server.port=8300

# DB
spring.datasource.url=${CORE_SERVICE_DATASOURCE_URL}
spring.datasource.username=${CORE_SERVICE_DB_USER}
spring.datasource.password=${CORE_SERVICE_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Keycloak
spring.security.oauth2.resourceserver.jwt.issuer-uri=${KEYCLOAK_OAUTH2_ISSUER_URI}