spring.application.name=core-service
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
spring.config.import=optional:configserver:http://localhost:8888/

# Stripe Configuration
# Replace these with your actual Stripe keys
stripe.api.key=sk_test_51TBad3LcmyjneUBCA0ssvNErtfvp72OsqtWc08DLvm9cWmqfyb7bLjPjq5WW8rsAHrAst7svnONEszWH94Q72JDa00K5bAp9AI
stripe.publishable.key=pk_test_51TBad3LcmyjneUBC8bVW2gVysEs0tD27olAtTwwpwfztVAMzOSX6fvQooMSiNQYjmIFgASW0jMq1Ik8jqH71CXfo00na6ZfiwE
stripe.webhook.secret=whsec_038XW6B5nla0uGw04Hmku6PA4LhlMAnk